pi_12 = cell2mat(arrayfun(@(exp_type_idx) repmat(pi_1(exp_type_idx, :), 3, 1),...
    (1:n_exp_types)', 'UniformOutput', false));
P2 = cell2mat(arrayfun(@(exp_type_idx) repmat(P(:, :, exp_type_idx), 1, 1, 3),...
    reshape(1:n_exp_types, 1, 1, n_exp_types), 'UniformOutput', false));
em2 = cell2mat(arrayfun(@(exp_type_idx) repmat(emission_means(exp_type_idx, :, :), 3, 1, 1),...
    (1:n_exp_types)', 'UniformOutput', false));
ec2 = cell2mat(arrayfun(@(exp_type_idx) repmat(emission_covs(:, :, :, exp_type_idx), 1, 1, 1, 3),...
    reshape(1:n_exp_types, 1, 1, 1, n_exp_types), 'UniformOutput', false));
