fisher_info = zeros(55, 55, 12);
tic;
parfor exp_idx = 1:12
    fisher_info(:, :, exp_idx) = approxFisherInfo2(pi_1(exp_idx, :),...
        P(:, :, exp_idx), emission_means(exp_idx, :, :),...
        chol_emission_covs(:, :, :, exp_idx), con_seq{exp_idx}, mu1(exp_idx, :),...
        chol_Sig1(:, :, exp_idx), l_dirs, orth_l_dirs, median_norm_u, movement_z,...
        1e-4, d_ec_inv_d_ec(:, :, :, :, :, exp_idx), 5e4);
    fprintf('Completed approximation for experiment: %d\n', exp_idx)
end
toc
save('fisher_info3_all_exp.mat', 'fisher_info')