n_ctrl = 20;
n_ad = 24;
n_pca = 6;
n_experiments = 12;
fisher_fv_ctrl = zeros(55, n_ctrl, n_experiments);
fisher_fv_ad = zeros(55, n_ad, n_experiments);
fisher_fv_pca = zeros(55, n_pca, n_experiments);
delta = 1e-2;
tic;
parfor exp_idx = 1:n_experiments
    theta_hat = {pi_1(exp_idx, :), P(:, :, exp_idx),...
        emission_means(exp_idx, :, :), emission_covs(:, :, :, exp_idx)};
    fisher_fv_ctrl(:, :, exp_idx) = cell2mat(arrayfun(@(person_idx)...
        approxGradLogLYU(y_exp{exp_idx}{person_idx},...
        p_ugx_exp{exp_idx}{person_idx}, theta_hat{:},...
        double(zero_prob_exp{exp_idx}{person_idx}), delta), 1:n_ctrl,...
        'UniformOutput', false));
    fprintf('Completed ctrl grad vectors for exp: %d\n', exp_idx)
    fisher_fv_ad(:, :, exp_idx) = cell2mat(arrayfun(@(person_idx)...
        approxGradLogLYU(y_ad_exp{exp_idx}{person_idx},...
        p_ugx_ad_exp{exp_idx}{person_idx}, theta_hat{:},...
        double(zero_prob_ad_exp{exp_idx}{person_idx}), delta), 1:n_ad,...
        'UniformOutput', false));
    fprintf('Completed ad grad vectors for exp: %d\n', exp_idx)
    fisher_fv_pca(:, :, exp_idx) = cell2mat(arrayfun(@(person_idx)...
        approxGradLogLYU(y_pca_exp{exp_idx}{person_idx},...
        p_ugx_pca_exp{exp_idx}{person_idx}, theta_hat{:},...
        double(zero_prob_pca_exp{exp_idx}{person_idx}), delta), 1:n_pca,...
        'UniformOutput', false));
    fprintf('Completed pca grad vectors for exp: %d\n', exp_idx)
end
toc