% fisher_fv_new = zeros(length(grad_ettl), n_ctrl, 3);
% fisher_fv_new_ad = zeros(length(grad_ettl), n_ad, 3);
% fisher_fv_new_pca = zeros(length(grad_ettl), n_pca, 3);
control_idx = setdiff(1:n_ctrl, 7);
tic;
for exp_idx = 2:3
    fprintf('experiment %d\n', exp_idx)
    for p_idx = 1:length(control_idx)
        person_idx = control_idx(p_idx);
        fprintf('\tControl individual %d\n', person_idx)
        [p_x, p_x_x_next] =...
            forwardBackward(y{person_idx}{exp1_idx(person_idx) + exp_idx - 1}(:, :, [1, (four_ld+1)]),...
            p_ugx{person_idx}{exp1_idx(person_idx) + exp_idx - 1}(:, [1, (four_ld+1)]),...
            pi_1, P, emission_means, emission_covs,...
            double(zero_prob{person_idx}{exp1_idx(person_idx) + exp_idx - 1}(:, four_ld)));
        fisher_fv_new(:, person_idx, exp_idx) =...
            gradETLL(p_x, p_x_x_next, pi_1, P, emission_means, emission_covs,...
            y{person_idx}{exp1_idx(person_idx) + exp_idx - 1}(:, :, [1, (four_ld+1)])) +...
            gradPosteriorEntropy(pi_1, P, emission_means, emission_covs,...
            y{person_idx}{exp1_idx(person_idx) + exp_idx - 1}(:, :, [1, (four_ld+1)]),...
            p_ugx{person_idx}{exp1_idx(person_idx) + exp_idx - 1}(:, [1, (four_ld+1)]),...
            double(zero_prob{person_idx}{exp1_idx(person_idx) + exp_idx - 1}(:, four_ld)), 1e-6);
    end
    fprintf('Controls completed\n')
    for person_idx = 1:n_ad
        fprintf('\tAD individual %d\n', person_idx)
        [p_x, p_x_x_next] =...
            forwardBackward(y_ad{person_idx}{exp1_idx_ad(person_idx) + exp_idx - 1}(:, :, [1, (four_ld+1)]),...
            p_ugx_ad{person_idx}{exp1_idx_ad(person_idx) + exp_idx - 1}(:, [1, (four_ld+1)]),...
            pi_1, P, emission_means, emission_covs,...
            double(zero_prob_ad{person_idx}{exp1_idx_ad(person_idx) + exp_idx - 1}(:, four_ld)));
        fisher_fv_new_ad(:, person_idx, exp_idx) =...
            gradETLL(p_x, p_x_x_next, pi_1, P, emission_means, emission_covs,...
            y_ad{person_idx}{exp1_idx_ad(person_idx) + exp_idx - 1}(:, :, [1, (four_ld+1)])) +...
            gradPosteriorEntropy(pi_1, P, emission_means, emission_covs,...
            y_ad{person_idx}{exp1_idx_ad(person_idx) + exp_idx - 1}(:, :, [1, (four_ld+1)]),...
            p_ugx_ad{person_idx}{exp1_idx_ad(person_idx) + exp_idx - 1}(:, [1, (four_ld+1)]),...
            double(zero_prob_ad{person_idx}{exp1_idx_ad(person_idx) + exp_idx - 1}(:, four_ld)), 1e-6);
    end
    fprintf('ADs completed\n')
    for person_idx = 1:n_pca
        fprintf('\tPCA individual %d\n', person_idx)
        [p_x, p_x_x_next] =...
            forwardBackward(y_pca{person_idx}{exp1_idx_pca(person_idx) + exp_idx - 1}(:, :, [1, (four_ld+1)]),...
            p_ugx_pca{person_idx}{exp1_idx_pca(person_idx) + exp_idx - 1}(:, [1, (four_ld+1)]),...
            pi_1, P, emission_means, emission_covs,...
            double(zero_prob_pca{person_idx}{exp1_idx_pca(person_idx) + exp_idx - 1}(:, four_ld)));
        fisher_fv_new_pca(:, person_idx, exp_idx) =...
            gradETLL(p_x, p_x_x_next, pi_1, P, emission_means, emission_covs,...
            y_pca{person_idx}{exp1_idx_pca(person_idx) + exp_idx - 1}(:, :, [1, (four_ld+1)])) +...
            gradPosteriorEntropy(pi_1, P, emission_means, emission_covs,...
            y_pca{person_idx}{exp1_idx_pca(person_idx) + exp_idx - 1}(:, :, [1, (four_ld+1)]),...
            p_ugx_pca{person_idx}{exp1_idx_pca(person_idx) + exp_idx - 1}(:, [1, (four_ld+1)]),...
            double(zero_prob_pca{person_idx}{exp1_idx_pca(person_idx) + exp_idx - 1}(:, four_ld)), 1e-6);
    end
end
fprintf('All individuals completed\n')
time_taken2 = toc;