likelihood_training = zeros(n_training_people, 1);
likelihood_test_control = zeros(size(y_exp1, 1) - n_training_people, 1);
likelihood_test_ad = zeros(n_ad_patients, 1);
likelihood_test_pca = zeros(n_pca_patients, 1);
for person_idx = 1:n_training_people
    likelihood_training(person_idx) =...
        logLikelihood(y_exp1{training_people(person_idx)}, pi_1_hat,...
        P_hat, emission_means_hat, emission_covs_hat,...
        double(zero_prob_exp1{training_people(person_idx)}));
end
for person_idx = 1:n_control_test
    likelihood_test_control(person_idx) =...
        logLikelihood(y_exp1{control_test_people(person_idx)}, pi_1_hat,...
        P_hat, emission_means_hat, emission_covs_hat,...
        double(zero_prob_exp1{control_test_people(person_idx)}));
end
for person_idx = 1:n_ad_patients
    likelihood_test_ad(person_idx) =...
        logLikelihood(y_ad_exp1{person_idx}, pi_1_hat,...
        P_hat, emission_means_hat, emission_covs_hat,...
        double(zero_prob_ad_exp1{person_idx}));
end
for person_idx = 1:n_pca_patients
    likelihood_test_pca(person_idx) =...
        logLikelihood(y_pca_exp1{person_idx}, pi_1_hat,...
        P_hat, emission_means_hat, emission_covs_hat,...
        double(zero_prob_pca_exp1{person_idx}));
end