tr_ind = 9; %lewwi
tr_ind_exp_idx = exp1_idx(tr_ind):n_experiments;
n_exp_types = 4;
% % y_tr = y{tr_ind}(exp1_idx(tr_ind):end);
% % zp_tr = zero_prob{tr_ind}(exp1_idx(tr_ind):end);
% % p_ugx_tr = p_ugx{tr_ind}(exp1_idx(tr_ind):end);

y_tr = arrayfun(@(exp_type_idx)...
    y{tr_ind}((3*(exp_type_idx-1)+exp1_idx(tr_ind)):(3*exp_type_idx+exp1_idx(tr_ind)-1)),...
    1:4, 'UniformOutput', false);
zp_tr = arrayfun(@(exp_type_idx)...
    arrayfun(@(exp_idx) double(zero_prob{tr_ind}{exp_idx}),...
    ((3*(exp_type_idx-1)+exp1_idx(tr_ind)):(3*exp_type_idx+exp1_idx(tr_ind)-1))',...
    'UniformOutput', false), 1:4, 'UniformOutput', false);
p_ugx_tr = arrayfun(@(exp_type_idx)...
    p_ugx{tr_ind}((3*(exp_type_idx-1)+exp1_idx(tr_ind)):(3*exp_type_idx+exp1_idx(tr_ind)-1)),...
    1:4, 'UniformOutput', false);
tic;
parfor idx = 1:n_exp_types
    fprintf('Beginning parameter estimation for experiment: %d\n', idx)
% %     y_training = arrayfun(@(person_idx)...
% %         y{training_group(person_idx)}{exp1_idx(training_group(person_idx))+idx},...
% %         (1:length(training_group))', 'UniformOutput', false);
% %     zero_prob_training = arrayfun(@(person_idx)...
% %         double(zero_prob{training_group(person_idx)}{exp1_idx(training_group(person_idx))+idx}),...
% %         (1:length(training_group))', 'UniformOutput', false);
% %     p_ugx_training = arrayfun(@(person_idx)...
% %         p_ugx{training_group(person_idx)}{exp1_idx(training_group(person_idx))+idx},...
% %         (1:length(training_group))', 'UniformOutput', false);
% %     [pi_1(idx+1, :), P(:, :, idx+1), emission_means(idx+1, :, :), emission_covs(:, :, :, idx+1)] =...
% %         EM_ManyPeopleMultipleRestarts(y_training, p_ugx_training, zero_prob_training, 500, 1e-5, 20, 1e-3);
% % %     [pi_1(idx, :), P(:, :, idx), emission_means(idx, :, :), emission_covs(:, :, :, idx)] =...
% % %         EM_MultipleRestarts(y_tr{idx}, p_ugx_tr{idx}, double(zp_tr{idx}),...
% % %         500, 20, 1e-5, 1e-3);
    [pi_1(idx, :), P(:, :, idx), emission_means(idx, :, :), emission_covs(:, :, :, idx)] =...
        EM_ManyPeopleMultipleRestarts(y_tr{idx}, p_ugx_tr{idx}, zp_tr{idx}, 500, 1e-5, 20, 1e-3);
end
toc